import alpaca_trade_api as tradeapi
import time
from datetime import datetime

# --- CONFIGURATION comment Videet

API_KEY = "PKJ6UV4G4PKYHMVZZFNFH77BNJ"
SECRET_KEY = "44GM1kfatyhB8wAvo3moUZqb7xRFUhYS4gaX1ZCqYNn8"
BASE_URL = "https://paper-api.alpaca.markets"

SYMBOLS = {
    "AAPL": 1,
    "MSFT": 1,
    "GOOGL": 1,
    "AMZN": 1,
    "NVDA": 1,
    "TSLA": 1,
    "META": 1,
    "BRK.B": 1,
    "UNH": 1,
    "XOM": 1,
    "JNJ": 1,
    "JPM": 1,
    "V": 1,
    "PG": 1,
    "MA": 1,
    "HD": 1,
    "CVX": 1,
    "MRK": 1,
    "ABBV": 1,
    "PEP": 1,
    "KO": 1,
    "AVGO": 1,
    "COST": 1,
    "WMT": 1,
    "BAC": 1,
    "TMO": 1,
    "MCD": 1,
    "CSCO": 1,
    "ACN": 1,
    "ABT": 1,
    "CRM": 1,
    "LLY": 1,
    "NFLX": 1,
    "NKE": 1,
    "WFC": 1,
    "DHR": 1,
    "TXN": 1,
    "ADBE": 1,
    "PM": 1,
    "NEE": 1,
    "RTX": 1,
    "BMY": 1,
    "SCHW": 1,
    "T": 1,
    "HON": 1,
    "AMGN": 1,
    "IBM": 1,
    "LOW": 1,
    "QCOM": 1,
    "CAT": 1,
    "GE": 1,
    "SBUX": 1,
    "INTU": 1,
    "BLK": 1,
    "MDT": 1,
    "SPGI": 1,
    "AMAT": 1,
    "CVS": 1,
    "GILD": 1,
    "MO": 1,
    "ADI": 1,
    "ISRG": 1,
    "NOW": 1,
    "ADP": 1,
    "REGN": 1,
    "MMC": 1,
    "MDLZ": 1,
    "SYK": 1,
    "C": 1,
    "ETN": 1,
    "ZTS": 1,
    "ITW": 1,
    "VRTX": 1,
    "BKNG": 1,
    "GS": 1,
    "TGT": 1,
    "PLD": 1,
    "DE": 1,
    "CI": 1,
    "LMT": 1,
    "CB": 1,
    "SHW": 1,
    "AMT": 1,
    "AON": 1,
    "LRCX": 1,
    "CME": 1,
    "NOC": 1,
    "USB": 1,
    "SO": 1,
    "D": 1,
    "DUK": 1,
    "APD": 1,
    "FDX": 1,
    "NSC": 1,
    "HUM": 1,
    "PNC": 1,
    "PSA": 1,
    "MMM": 1,
    "ICE": 1,
    "MCO": 1,
    "EW": 1,
    "IQV": 1,
    "TROW": 1,
    "WM": 1,
    "IDXX": 1,
    "AIG": 1,
    "KLAC": 1,
    "MSI": 1,
    "ECL": 1,
    "SRE": 1,
    "ROP": 1,
    "HCA": 1,
    "AFL": 1,
    "SBAC": 1,
    "TT": 1,
    "GWW": 1,
    "FTNT": 1,
    "CTSH": 1,
    "EXC": 1,
    "PCAR": 1,
    "PH": 1,
    "PPL": 1,
    "WELL": 1,
    "CARR": 1,
    "AEP": 1,
    "STT": 1,
    "MCHP": 1,
    "OXY": 1,
    "BDX": 1,
    "ALL": 1,
    "ADM": 1,
    "TEL": 1,
    "CDNS": 1,
    "TRV": 1,
    "PAYX": 1,
    "CTAS": 1,
    "YUM": 1,
    "BIIB": 1,
    "KEYS": 1,
    "VRSK": 1,
    "AME": 1,
    "FAST": 1,
    "KMB": 1,
    "ROK": 1,
    "AEE": 1,
    "DOV": 1,
    "MTD": 1,
    "AWK": 1,
    "WAT": 1,
    "ANSS": 1,
    "OTIS": 1,
    "XEL": 1,
    "PAYC": 1,
    "DLTR": 1,
    "CHD": 1,
    "BR": 1,
    "GNRC": 1,
    "LH": 1,
    "GPN": 1,
    "IEX": 1,
    "CBRE": 1,
    "EXPD": 1,
    "NDAQ": 1,
    "FDS": 1,
    "FRC": 1,
    "WTW": 1,
    "IT": 1,
    "OMC": 1,
    "HBAN": 1,
    "RF": 1,
    "CFG": 1,
    "CBOE": 1,
    "CINF": 1,
    "ZBRA": 1,
    "TFX": 1,
    "L": 1,
    "LDOS": 1,
    "HOLX": 1,
    "TSCO": 1,
    "FOX": 1,
    "NVR": 1,
    "LUV": 1,
    "ALB": 1,
    "WRB": 1,
    "UAL": 1,
    "DAL": 1,
    "AAL": 1,
    "EXPE": 1,
    "MGM": 1,
    "LVS": 1,
    "CZR": 1,
    "PENN": 1,
    "WYNN": 1,
    "MAR": 1,
    "HLT": 1,
    "H": 1,
    "CCL": 1,
    "RCL": 1,
    "NCLH": 1,
    "DIS": 1,
    "CMCSA": 1,
    "CHTR": 1,
    "FOXA": 1,
    "PARA": 1,
    "DISCA": 1,
    "WBD": 1,
    "VIAC": 1,
    "SIRI": 1,
    "NYT": 1,
    "SON": 1,
    "MKC": 1,
    "CLX": 1,
    "CAG": 1,
    "SJM": 1,
    "HRL": 1,
    "MHK": 1,
    "LEG": 1,
    "TPR": 1,
    "PVH": 1,
    "RL": 1,
    "HBI": 1,
    "NWL": 1,
    "WHR": 1,
    "KMX": 1,
    "AN": 1,
    "PAG": 1,
    "AZO": 1,
    "ORLY": 1,
    "AAP": 1,
    "GPC": 1,
    "BWA": 1,
    "LEA": 1,
    "LKQ": 1,
    "ALV": 1,
    "APTV": 1,
    "MGA": 1,
    "TEN": 1,
    "DAN": 1,
    "NAPA": 1,
    "MTOR": 1,
    "SMP": 1,
    "DORM": 1,
    "MODG": 1,
    "F": 1,
    "GM": 1,
    "STLA": 1,
    "TM": 1,
    "HMC": 1,
    "NSANY": 1,
    "VWAGY": 1,
    "BMWYY": 1,
    "DDAIF": 1,
    "COP": 1,
    "EOG": 1,
    "PXD": 1,
    "DVN": 1,
    "HES": 1,
    "MPC": 1,
    "VLO": 1,
    "PSX": 1,
    "OKE": 1,
    "KMI": 1,
    "WMB": 1,
    "ET": 1,
    "EPD": 1,
    "PAA": 1,
    "MPLX": 1,
    "DCP": 1,
    "TRGP": 1,
    "ENLC": 1,
    "WEC": 1,
    "ES": 1,
    "DTE": 1,
    "FE": 1,
    "ETR": 1,
    "EIX": 1,
    "PEG": 1,
    "CMS": 1,
    "NI": 1,
    "OGE": 1,
    "CLECO": 1,
    "CCI": 1,
    "DLR": 1,
    "EQIX": 1,
    "EXR": 1,
    "CUBE": 1,
    "LSI": 1,
    "NSA": 1,
    "EGP": 1,
    "REXR": 1,
    "FR": 1,
    "STAG": 1,
    "TRNO": 1,
    "COLD": 1,
    "LPT": 1,
    "HIW": 1,
    "BXP": 1,
    "VNO": 1,
    "SLG": 1,
    "KRC": 1,
    "DEI": 1,
    "PDM": 1,
    "CLI": 1,
    "VRE": 1,
    "JBGS": 1,
    "EQC": 1,
    "PGRE": 1,
    "MAA": 1,
    "CPT": 1,
    "AIV": 1,
    "UDR": 1,
    "EQR": 1,
    "ESS": 1,
    "NMI": 1,
    "IRT": 1,
    "NXRT": 1,
    "APTS": 1,
    "O": 1,
    "NNN": 1,
    "STOR": 1,
    "EPRT": 1,
    "ADC": 1,
    "AGREE": 1,
    "GTY": 1,
    "NTST": 1,
    "PINE": 1,
    "PREIT": 1,
    "WPC": 1,
    "SRC": 1,
    "SPIRIT": 1,
    "GNL": 1,
    "RTL": 1,
    "NLCP": 1,
    "FCPT": 1,
    "BNL": 1,
    "PECO": 1,
    "IIPR": 1,
    "PW": 1,
    "GIPR": 1,
    "LAND": 1,
    "AFCG": 1,
    "KREF": 1,
    "TRTX": 1,
    "ACRE": 1,
    "BXMT": 1,
    "ARI": 1,
    "LADR": 1,
    "MS": 1,
    "TFC": 1,
    "COF": 1,
    "AXP": 1,
    "DFS": 1,
    "SYF": 1,
    "ALLY": 1,
    "NAVI": 1,
    "CACC": 1,
    "SC": 1,
    "OMF": 1,
    "ENVA": 1,
    "WRLD": 1,
    "BRK.A": 1,
    "MET": 1,
    "PRU": 1,
    "PGR": 1,
    "HIG": 1,
    "CNC": 1,
    "MOH": 1,
    "ELV": 1,
    "WCG": 1,
    "MGLN": 1,
    "ACET": 1,
    "A": 1,
    "BIO": 1,
    "IQVIA": 1,
    "NTRA": 1,
    "ILMN": 1,
    "PACB": 1,
    "BEAM": 1,
    "EDIT": 1,
    "CRSP": 1,
    "NTLA": 1,
    "SGMO": 1,
    "FATE": 1,
    "ALNY": 1,
    "IONS": 1,
    "MRNA": 1,
    "BNTX": 1,
    "PFE": 1,
    "AZN": 1,
    "GSK": 1,
    "NVO": 1,
    "SNY": 1,
    "RHHBY": 1,
    "NOVN": 1,
    "ALXN": 1,
    "BMRN": 1,
    "SGEN": 1,
    "RARE": 1,
    "LGND": 1,
    "JAZZ": 1,
    "INCY": 1,
    "EXEL": 1,
    "HALO": 1,
    "PTCT": 1,
    "ONCE": 1,
    "BSX": 1,
    "ZBH": 1,
    "DXCM": 1,
    "PODD": 1,
    "INSP": 1,
    "NVCR": 1,
    "RMD": 1,
    "PHG": 1,
    "IART": 1,
    "ATRC": 1,
    "NVST": 1,
    "HSIC": 1,
    "XRAY": 1,
    "PDCO": 1,
    "ABMD": 1,
    "LMAT": 1,
    "INTUITY": 1,
    "NARI": 1,
    "SI": 1,
    "SWAV": 1,
    "TMDX": 1,
    "NVRO": 1,
    "GKOS": 1,
    "AXNX": 1,
    "AFIB": 1,
    "PTC": 1,
    "EPAM": 1,
    "MANH": 1,
    "VEEV": 1,
    "WDAY": 1,
    "TEAM": 1,
    "DDOG": 1,
    "MDB": 1,
    "SNOW": 1,
    "ZS": 1,
    "CRWD": 1,
    "OKTA": 1,
    "NET": 1,
    "PANW": 1,
    "CYBR": 1,
    "VRNT": 1,
    "SAIL": 1,
    "QLYS": 1,
    "S": 1,
    "RPD": 1,
    "TENB": 1,
    "RDWR": 1,
    "CHKP": 1,
    "ORCL": 1,
    "SAP": 1,
    "HPE": 1,
    "HPQ": 1,
    "DELL": 1,
    "NTAP": 1,
    "STX": 1,
    "WDC": 1,
    "SNDK": 1,
    "MU": 1,
    "INTC": 1,
    "AMD": 1,
    "SWKS": 1,
    "QRVO": 1,
    "SLAB": 1,
    "MPWR": 1,
    "AAON": 1,
    "FORM": 1,
    "POWI": 1,
    "IXYS": 1,
    "ONTO": 1,
    "CEVA": 1,
    "AOSL": 1,
}

# Initialize API
api = tradeapi.REST(API_KEY, SECRET_KEY, BASE_URL, api_version='v2')

def run_trader():
    print(f"--- BOT ATTEMPTING START AT {datetime.now().strftime('%H:%M:%S')} ---", flush=True)
    
    try:
        print("Checking connection to Alpaca...", flush=True)
        account = api.get_account()
        print(f"CONNECTED! Account Status: {account.status} | Balance: ${account.cash}", flush=True)
    except Exception as e:
        print(f"!!! CONNECTION ERROR: {e}", flush=True)
        return

    print(f"Monitoring: {', '.join(SYMBOLS.keys())}", flush=True)
    print("------------------------------------------", flush=True)

    while True:
        for SYMBOL, QTY in SYMBOLS.items():
            try:
                bars = api.get_bars(SYMBOL, tradeapi.TimeFrame.Minute, limit=20).df

                if bars.empty:
                    print(f"[{datetime.now().strftime('%H:%M:%S')}] {SYMBOL}: No data received. Is the market open?", flush=True)
                    continue

                current_price = bars['close'].iloc[-1]
                sma = bars['close'].mean()

                try:
                    api.get_position(SYMBOL)
                    holding = "YES"
                except:
                    holding = "NO"

                timestamp = datetime.now().strftime("%H:%M:%S")
                print(f"[{timestamp}] {SYMBOL} | PRICE: ${current_price:<8.2f} | SMA: ${sma:<8.2f} | HOLDING: {holding}", flush=True)

                if current_price < (sma * 0.998) and holding == "NO":
                    print(f">>> SIGNAL: BUY {SYMBOL}", flush=True)
                    api.submit_order(symbol=SYMBOL, qty=QTY, side='buy', type='market', time_in_force='gtc')

                elif current_price > (sma * 1.002) and holding == "YES":
                    print(f">>> SIGNAL: SELL {SYMBOL}", flush=True)
                    api.submit_order(symbol=SYMBOL, qty=QTY, side='sell', type='market', time_in_force='gtc')

            except Exception as e:
                print(f"!!! ERROR on {SYMBOL}: {e}", flush=True)

        time.sleep(60)

if __name__ == "__main__":
    run_trader()
